"""002_add_use_cases_and_catalog

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSON
import uuid

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create use_case_catalog table
    op.create_table('use_case_catalog',
        sa.Column('id', UUID(as_uuid=True), default=uuid.uuid4, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('sector', sa.String(length=100), nullable=False),
        sa.Column('typical_ai_act_level', sa.String(length=50), nullable=False),
        sa.Column('template_data', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_case_catalog_sector'), 'use_case_catalog', ['sector'], unique=False)
    
    # Create use_cases table
    op.create_table('use_cases',
        sa.Column('id', UUID(as_uuid=True), default=uuid.uuid4, nullable=False),
        sa.Column('organization_id', UUID(as_uuid=True), nullable=False),
        sa.Column('catalog_id', UUID(as_uuid=True), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('sector', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
        sa.Column('ai_act_level', sa.String(length=50), server_default='unclassified', nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('classification_reason', sa.String(), nullable=True),
        sa.Column('classification_data', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['catalog_id'], ['use_case_catalog.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_cases_organization_id'), 'use_cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_use_cases_catalog_id'), 'use_cases', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_use_cases_sector'), 'use_cases', ['sector'], unique=False)
    op.create_index(op.f('ix_use_cases_status'), 'use_cases', ['status'], unique=False)
    op.create_index(op.f('ix_use_cases_ai_act_level'), 'use_cases', ['ai_act_level'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_use_cases_ai_act_level'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_status'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_sector'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_catalog_id'), table_name='use_cases')
    op.drop_index(op.f('ix_use_cases_organization_id'), table_name='use_cases')
    op.drop_table('use_cases')
    op.drop_index(op.f('ix_use_case_catalog_sector'), table_name='use_case_catalog')
    op.drop_table('use_case_catalog')
    # ### end Alembic commands ###
