-- Data: 20260408100000_initial_data.sql

-- Insert into risk_catalog
INSERT INTO risk_catalog (name, description, ai_act_article, ai_act_level, category, sector_tags) VALUES
('Manipulación subliminal de comportamiento', 'Sistemas que utilizan técnicas subliminales para influir en el comportamiento de las personas de forma perjudicial.', 'Art. 5.1.a', 'prohibited', 'manipulacion', '["general"]'),
('Explotación de vulnerabilidades de grupos vulnerables', 'Sistemas diseñados para explotar las vulnerabilidades de grupos específicos (niños, personas con discapacidad) para causarles daño.', 'Art. 5.1.b', 'prohibited', 'vulnerabilidad', '["general"]'),
('Scoring social por gobiernos', 'Sistemas utilizados por autoridades públicas para evaluar o clasificar la fiabilidad de personas físicas basándose en su comportamiento social.', 'Art. 5.1.c', 'prohibited', 'scoring_social', '["gobierno", "seguridad"]'),
('Evaluación de riesgo de reincidencia (profiling)', 'Sistemas que evalúan el riesgo de reincidencia de una persona basándose en su perfil o características personales.', 'Art. 5.1.d', 'prohibited', 'reincidencia', '["justicia", "seguridad"]'),
('Raspado de bases de datos biométricas no autorizadas', 'Uso de datos biométricos obtenidos sin consentimiento o de forma no autorizada para identificación o categorización.', 'Art. 5.1.e', 'prohibited', 'biometrico', '["seguridad", "privacidad"]'),
('Inferencia de emociones en trabajo/educación', 'Sistemas que infieren estados emocionales en el lugar de trabajo o en instituciones educativas, salvo excepciones específicas.', 'Art. 5.1.f', 'prohibited', 'emocional', '["empleo", "educacion"]'),
('Categorización biométrica sensible', 'Sistemas que categorizan datos biométricos sensibles (ej. orientación sexual, ideología) sin base legal clara o consentimiento.', 'Art. 5.1.g', 'prohibited', 'biometrico', '["privacidad", "salud"]'),
('Identificación biométrica remota en tiempo real', 'Sistemas de identificación biométrica remota en tiempo real, excepto en casos de aplicación de la ley con garantías legales.', 'Art. 5.1.h', 'prohibited', 'biometrico', '["seguridad", "ley"]'),
('Sistemas críticos para infraestructura', 'IA utilizada en la gestión y operación de infraestructuras críticas (ej. transporte, energía, agua).', 'Art. 6.1', 'high_risk', 'infraestructura', '["transporte", "energia", "agua", "salud"]'),
('Sistemas educativos y de evaluación vocacional', 'IA utilizada para el acceso o el ejercicio de actividades educativas y de formación profesional.', 'Art. 6.2', 'high_risk', 'educacion', '["educacion", "empleo"]'),
('Sistemas de contratación y gestión laboral', 'IA utilizada para la contratación, selección de personal, o gestión de relaciones laborales.', 'Art. 6.3', 'high_risk', 'empleo', '["empleo"]'),
('Sistemas de acceso a servicios esenciales', 'IA utilizada para evaluar el acceso a servicios esenciales y públicos (ej. crédito, seguros, salud).', 'Art. 6.4', 'high_risk', 'servicios_esenciales', '["finanzas", "seguros", "salud", "gobierno"]'),
('Sistemas de evaluación de solicitudes de asilo/visado', 'IA utilizada para evaluar solicitudes de asilo, visados y permisos de residencia.', 'Art. 6.5', 'high_risk', 'migracion', '["gobierno", "justicia"]'),
('Sistemas de asistencia judicial y policial', 'IA utilizada en la aplicación de la ley, investigación criminal, evaluación de riesgo y asistencia judicial.', 'Art. 6.6, 6.7', 'high_risk', 'justicia', '["justicia", "seguridad", "ley"]'),
('Sistemas de administración de justicia/democracia', 'IA utilizada para influir en los procesos electorales o judiciales.', 'Art. 6.8', 'high_risk', 'democracia', '["gobierno", "justicia"]'),
('Sistemas de gestión de migración/fronteras', 'IA utilizada en la gestión de la migración, control de fronteras y seguridad fronteriza.', 'Art. 6.9', 'high_risk', 'migracion', '["gobierno", "seguridad"]'),
('Uso de chatbots en atención al cliente', 'IA utilizada como interfaz de conversación en atención al cliente.', 'Art. 52', 'limited_risk', 'interaccion_usuario', '["servicio_cliente", "finanzas", "retail"]'),
('Generación de contenido con IA', 'IA utilizada para generar texto, imágenes o audio.', 'Art. 52', 'limited_risk', 'contenido_generado', '["marketing", "medios", "educacion"]'),
('Sistemas de recomendación', 'IA utilizada para recomendar productos, servicios o contenido a usuarios.', 'Art. 52', 'limited_risk', 'recomendacion', '["retail", "medios", "entretenimiento"]'),
('Sistema de monitoreo de cumplimiento normativo', 'IA que monitoriza el cumplimiento de normativas internas o externas.', 'Art. 52', 'limited_risk', 'cumplimiento', '["legal", "finanzas", "gobierno"]');

-- Insert into control_catalog
INSERT INTO control_catalog (name, description, implementation_guide, ai_act_level, category, related_risk_ids) VALUES
('Documentación detallada del sistema', 'Mantener documentación exhaustiva sobre el diseño, desarrollo, funcionamiento y uso del sistema IA.', 'Crear y mantener un repositorio centralizado con toda la documentación técnica y de usuario.', 'high_risk', 'documentacion', ARRAY['88967566-07b6-4410-ac06-c39e16475013', '99f0f2c0-b28f-4533-887d-75b688a91234', 'c2c7a6c2-45f3-4e3e-a6d4-86a1a0851943']),
('Sistema de gestión de riesgos', 'Establecer y mantener un sistema de gestión de riesgos para identificar, analizar, evaluar y tratar los riesgos asociados al sistema IA.', 'Implementar un marco de gestión de riesgos (ej. ISO 31000) adaptado a IA.', 'high_risk', 'gestion_riesgos', ARRAY['88967566-07b6-4410-ac06-c39e16475013', '99f0f2c0-b28f-4533-887d-75b688a91234', 'c2c7a6c2-45f3-4e3e-a6d4-86a1a0851943']),
('Gestión de datos de entrenamiento', 'Asegurar la calidad, integridad y representatividad de los datos de entrenamiento para mitigar sesgos y errores.', 'Implementar procesos de curación, validación y auditoría de datos.', 'high_risk', 'gestion_datos', ARRAY['88967566-07b6-4410-ac06-c39e16475013', '99f0f2c0-b28f-4533-887d-75b688a91234']),
('Logs de auditoría y registro', 'Implementar un sistema de registro detallado de eventos y operaciones para facilitar la auditoría y la trazabilidad.', 'Configurar logs que capturen la actividad del sistema, decisiones y operaciones críticas.', 'high_risk', 'auditoria', ARRAY['88967566-07b6-4410-ac06-c39e16475013', 'c2c7a6c2-45f3-4e3e-a6d4-86a1a0851943']),
('Transparencia para usuarios', 'Informar claramente a los usuarios sobre la presencia e interacciones con un sistema IA.', 'Utilizar avisos claros y accesibles durante la interacción del usuario.', 'limited_risk', 'transparencia', ARRAY['f5c3b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d', 'e1a7b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d']),
('Marcado de contenido generado por IA', 'Identificar y marcar explícitamente el contenido (texto, imágenes, audio) generado por IA.', 'Añadir metadatos o etiquetas visibles que indiquen la autoría por IA.', 'limited_risk', 'contenido_generado', ARRAY['f5c3b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d', 'e1a7b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d']),
('Supervisión humana', 'Asegurar la supervisión humana adecuada para monitorizar el funcionamiento del sistema y intervenir cuando sea necesario.', 'Establecer roles y procedimientos para la supervisión y la intervención humana.', 'high_risk', 'supervision_humana', ARRAY['88967566-07b6-4410-ac06-c39e16475013']),
('Exactitud y robustez', 'Garantizar que el sistema IA sea preciso, fiable y robusto ante posibles errores o resultados inesperados.', 'Realizar pruebas rigurosas de precisión, rendimiento y resistencia a fallos.', 'high_risk', 'exactitud', ARRAY['88967566-07b6-4410-ac06-c39e16475013', 'c2c7a6c2-45f3-4e3e-a6d4-86a1a0851943']),
('Ciberseguridad', 'Proteger el sistema IA contra ciberamenazas, asegurando la confidencialidad, integridad y disponibilidad de los datos y el sistema.', 'Implementar medidas de seguridad (encriptación, firewalls, control de acceso).', 'high_risk', 'ciberseguridad', ARRAY['88967566-07b6-4410-ac06-c39e16475013', 'c2c7a6c2-45f3-4e3e-a6d4-86a1a0851943']),
('Plan de desmantelamiento', 'Definir un plan para desmantelar de forma segura y progresiva los sistemas IA prohibidos si ya existen.', 'Establecer procedimientos claros para la desactivación y eliminación de datos.', 'prohibited', 'desmantelamiento', ARRAY['7a3a7c26-3f7e-40b0-a8b9-8d0d0b9b2a6f', '9d3f8c4e-5a4a-4b2a-8a1b-2c3d4e5f6a7b']),
('Transparencia básica', 'Proporcionar información general sobre el propósito y funcionamiento del sistema IA.', 'Incluir avisos generales o información en sitios web.', 'minimal_risk', 'transparencia', ARRAY['f5c3b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d']),
('Evaluación de impacto en derechos fundamentales', 'Realizar evaluaciones obligatorias para sistemas de alto riesgo antes de su puesta en el mercado.', 'Documentar y analizar potenciales impactos negativos en derechos fundamentales. Incorporar procesos de consulta.', 'high_risk', 'derechos_fundamentales', ARRAY['88967566-07b6-4410-ac06-c39e16475013']),
('Registro de actividad del usuario', 'Los usuarios deben poder ver un registro de sus propias interacciones y datos procesados por el sistema IA.', 'Proporcionar una interfaz para que los usuarios accedan a su historial de datos y actividad.', 'limited_risk', 'privacidad', ARRAY['f5c3b7c2-0f5d-4a0b-9f2d-1c4d1b6d7f8d']),
('Evaluación de la conformidad', 'Procedimientos para evaluar y certificar que un sistema IA de alto riesgo cumple con los requisitos del reglamento.', 'Contratar organismos notificados para auditorías y certificaciones.', 'high_risk', 'conformidad', ARRAY['88967566-07b6-4410-ac06-c39e16475013']),
('Gestión de la debida diligencia de terceros', 'Si se utilizan componentes de IA de terceros, se deben aplicar las mismas exigencias de evaluación.', 'Verificar que los proveedores externos cumplen con los requisitos del AI Act.', 'high_risk', 'terceros', ARRAY['88967566-07b6-4410-ac06-c39e16475013']),
('Aviso de manipulación', 'Avisar explícitamente si un sistema está diseñado para manipular.', 'Incluir advertencias claras y visibles en la interfaz.', 'prohibited', 'manipulacion', ARRAY['7a3a7c26-3f7e-40b0-a8b9-8d0d0b9b2a6f']);
